apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xrootd
  namespace: flux-system
spec:
  interval: 5m
  releaseName: xrootd
  targetNamespace: dep-dlm-PLACEHOLDER
  install: { createNamespace: true }
  dependsOn:
    - { name: external-secrets }
  chart:
    spec:
      chart: deploy/helm-charts/xrootd          # path within the GitRepository
      sourceRef: { kind: GitRepository, name: dep-dlm-testbed, namespace: flux-system }
  valuesFrom:
    - kind: ConfigMap
      name: xrootd-values
      valuesKey: xrootd.yaml
