apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "teapot.fullname" . }}
  labels:
    app: {{ include "teapot.name" . }}
    instance: {{ include "teapot.fullname" . }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "teapot.name" . }}
      instance: {{ include "teapot.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "teapot.name" . }}
        instance: {{ include "teapot.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 101
      hostname: {{ include "teapot.fullname" . }}
      initContainers:
        - name: fix-data-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 100:101 /data"]
          volumeMounts:
            - name: teapot-data
              mountPath: /data
      containers:
        - name: teapot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SSL_CERT_FILE
              value: /etc/ssl/certs/ca-certificates.crt
            - name: REQUESTS_CA_BUNDLE
              value: /etc/ssl/certs/ca-certificates.crt
          ports:
            - name: https
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - curl
                - -sk
                - https://localhost:8081/docs
                - -o
                - /dev/null
                - -w
                - "'%{http_code}'"
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          volumeMounts:
            {{- range $mount := .Values.volumeMounts }}
            - name: {{ $mount.name }}
              mountPath: {{ $mount.mountPath }}
              {{- if hasKey $mount "subPath" }}
              subPath: {{ tpl $mount.subPath $ }}
              {{- end }}
              {{- if hasKey $mount "readOnly" }}
              readOnly: {{ $mount.readOnly }}
              {{- end }}
            {{- end }}
            - name: teapot-data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
