fullnameOverride: keycloak
volumes:
  - name: certs
    secret:
      secretName: testbed-certs
  - name: secrets
    secret:
      secretName: testbed-secrets
volumeMounts:
  - { name: certs,   mountPath: /etc/x509/https/keycloakcert.pem, subPath: keycloakcert.pem, readOnly: true }
  - { name: certs,   mountPath: /etc/x509/https/keycloakkey.pem,  subPath: keycloakkey.pem,  readOnly: true }
  - { name: secrets, mountPath: /opt/keycloak/data/import/realm.json, subPath: realm.json,   readOnly: true }
