ftsdb:
  enabled: false

env:
  - name: REQUESTS_CA_BUNDLE
    value: /etc/pki/tls/certs/ca-bundle.crt
  - name: X509_USER_PROXY
    value: /tmp/x509up_u0
  - name: XrdSecGSISRVNAMES
    value: "*"
  - name: XrdSecGSIDELEGPROXY
    value: "2"
  - name: VALSTORAGE_IP
    valueFrom:
      secretKeyRef:
        name: testbed-secrets
        key: valstorage-ip
        optional: true
  - name: VALSTORAGE_HOST
    value: "valstorage.dep-dlm-staging.example.com"

volumes:
  - name: certs
    secret:
      secretName: testbed-certs
      defaultMode: 0600
      items:
        - { key: hostcert.pem,            path: hostcert.pem,            mode: 0600 }
        - { key: hostkey.pem,             path: hostkey.pem,             mode: 0600 }
        - { key: rucio_ca.pem,            path: rucio_ca.pem,            mode: 0644 }
        - { key: 5fca1cb1.0,              path: 5fca1cb1.0,              mode: 0644 }
        - { key: 5fca1cb1.signing_policy, path: 5fca1cb1.signing_policy, mode: 0644 }
  - name: secrets
    secret:
      secretName: testbed-secrets
      items:
        - { key: fts3config,           path: fts3config,           mode: 0644 }
        - { key: fts3restconfig, path: fts3restconfig, mode: 0644 }
        - { key: docker-entrypoint.sh, path: docker-entrypoint.sh, mode: 0755 }
  - name: configs
    configMap:
      name: testbed-configs
      items:
        - { key: gfal2_http_plugin.conf, path: gfal2_http_plugin.conf, mode: 0644 }

  - name: scripts
    configMap:
      name: testbed-scripts

  - name: patches
    configMap:
      name: testbed-patches

volumeMounts:
  - { name: certs, mountPath: /etc/grid-security/hostcert.pem, subPath: hostcert.pem }
  - { name: certs, mountPath: /etc/grid-security/hostkey.pem,  subPath: hostkey.pem }
  - { name: certs, mountPath: /etc/grid-security/certificates/5fca1cb1.0,              subPath: 5fca1cb1.0 }
  - { name: certs, mountPath: /etc/grid-security/certificates/5fca1cb1.signing_policy, subPath: 5fca1cb1.signing_policy }
  - { name: certs, mountPath: /etc/pki/ca-trust/source/anchors/rucio-ca.crt, subPath: rucio_ca.pem }
  - { name: secrets, mountPath: /etc/fts3/fts3config, subPath: fts3config }
  - { name: secrets, mountPath: /etc/fts3/fts3restconfig, subPath: fts3restconfig }
  - { name: configs, mountPath: /etc/gfal2.d/http_plugin.conf, subPath: gfal2_http_plugin.conf }
  - { name: secrets, mountPath: /docker-entrypoint.sh, subPath: docker-entrypoint.sh }
  - { name: patches, mountPath: /tmp/fts-rest-flask/src/fts3rest/fts3rest/config/middleware.py, subPath: fts--middleware.py }
  - { name: patches, mountPath: /tmp/fts-rest-flask/src/fts3rest/fts3rest/lib/openidconnect.py, subPath: fts--openidconnect.py }
  - { name: patches, mountPath: /tmp/fts-rest-flask/src/fts3rest/fts3rest/lib/JobBuilder.py,     subPath: fts--JobBuilder.py }
  - { name: patches, mountPath: /tmp/fts-rest-flask/src/fts3rest/fts3rest/model/cloudStorage.py,     subPath: fts--cloudStorage.py }
  - { name: patches, mountPath: /tmp/fts-rest-flask/src/fts3rest/fts3rest/controllers/config/cloud.py, subPath: fts--cloud.py }
  - { name: patches, mountPath: /tmp/fts-rest-flask/src/fts3rest/fts3rest/controllers/config/tokenproviders.py, subPath: fts--tokenproviders.py }
