apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: testbed-patches
spec:
  refreshInterval: 1h
  secretStoreRef: { name: dep-dlm-secrets, kind: ClusterSecretStore }
  target: { name: testbed-patches, creationPolicy: Owner }
  dataFrom:
    - extract: { key: dep-dlm-production-patches }
