{{- if (index .Values "rucio-server" "enabled") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rucio-server-cfg
  labels:
    app.kubernetes.io/name: dep-dlm-testbed
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{- $profile := .Values.global.scopeProfile }}
  {{- $pdir := "" }}
  {{- if ne $profile "local" }}{{ $pdir = printf "%s/" $profile }}{{- end }}
  {{- $cfgFile := "server.token-exchange.cfg" }}
  {{- if ne .Values.global.tokenMode "managed" }}{{ $cfgFile = "server.client-credentials.cfg" }}{{- end }}
  {{- $cfgPath := printf "files/configs/rucio/%s%s" $pdir $cfgFile }}
  {{- if not (.Files.Glob $cfgPath) }}{{ $cfgPath = printf "files/configs/rucio/%s" $cfgFile }}{{- end }}
  {{- $idpPath := printf "files/configs/rucio/%sidpsecrets.json" $pdir }}
  {{- if not (.Files.Glob $idpPath) }}{{ $idpPath = "files/configs/rucio/idpsecrets.json" }}{{- end }}
  server.cfg: {{ .Files.Get $cfgPath | b64enc }}
  alembic.ini: {{ .Files.Get "files/configs/rucio/alembic.ini" | b64enc }}
  idpsecrets.json: {{ .Files.Get $idpPath | b64enc }}
{{- end }}
