{{- if (index .Values "rucio-server" "enabled") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rucio-server-cfg
  labels:
    app.kubernetes.io/name: dep-dlm-testbed
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{- if eq .Values.global.tokenMode "managed" }}
  server.cfg: {{ .Files.Get "files/configs/rucio/server.token-exchange.cfg" | b64enc }}
  {{- else }}
  server.cfg: {{ .Files.Get "files/configs/rucio/server.client-credentials.cfg" | b64enc }}
  {{- end }}
  alembic.ini: {{ .Files.Get "files/configs/rucio/alembic.ini" | b64enc }}
  idpsecrets.json: {{ .Files.Get "files/configs/rucio/idpsecrets.json" | b64enc }}
{{- end }}
