{{- if .Values.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: testbed-secrets
  labels:
    app.kubernetes.io/name: dep-dlm-testbed
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{- $profile := .Values.global.scopeProfile }}
  {{- $flow := .Values.global.tokenMode }}
  {{- $pdir := "" }}
  {{- if ne $profile "local" }}{{ $pdir = printf "%s/" $profile }}{{- end }}
  {{- $cfgFile := "server.token-exchange.cfg" }}
  {{- if ne $flow "managed" }}{{ $cfgFile = "server.client-credentials.cfg" }}{{- end }}
  {{- $cfgPath := printf "files/configs/rucio/%s%s" $pdir $cfgFile }}
  {{- if not (.Files.Glob $cfgPath) }}{{ $cfgPath = printf "files/configs/rucio/%s" $cfgFile }}{{- end }}
  {{- $idpPath := printf "files/configs/rucio/%sidpsecrets.json" $pdir }}
  {{- if not (.Files.Glob $idpPath) }}{{ $idpPath = "files/configs/rucio/idpsecrets.json" }}{{- end }}
  {{- $fts3configPath := printf "files/configs/fts/%sfts3config" $pdir }}
  {{- if not (.Files.Glob $fts3configPath) }}{{ $fts3configPath = "files/configs/fts/fts3config" }}{{- end }}
  {{- $fts3restconfigFile := "unmanaged.fts3restconfig" }}
  {{- if eq $flow "managed" }}{{ $fts3restconfigFile = "managed.fts3restconfig" }}{{- end }}
  {{- $fts3restconfigPath := printf "files/configs/fts/%s%s" $pdir $fts3restconfigFile }}
  {{- if not (.Files.Glob $fts3restconfigPath) }}{{ $fts3restconfigPath = printf "files/configs/fts/%s" $fts3restconfigFile }}{{- end }}
  server.cfg: {{ .Files.Get $cfgPath | b64enc }}
  alembic.ini: {{ .Files.Get "files/configs/rucio/alembic.ini" | b64enc }}
  idpsecrets.json: {{ .Files.Get $idpPath | b64enc }}
  fts3config: {{ .Files.Get $fts3configPath | b64enc }}
  fts3restconfig: {{ .Files.Get $fts3restconfigPath | b64enc }}
  {{- if .Files.Get "files/configs/keycloak/realm.json" }}
  realm.json: {{ .Files.Get "files/configs/keycloak/realm.json" | b64enc }}
  {{- end }}
  {{- if .Files.Get "files/configs/rucio/userpass-client.cfg" }}
  userpass-client.cfg: {{ .Files.Get "files/configs/rucio/userpass-client.cfg" | b64enc }}
  {{- end }}
{{- end }}
