apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dep-dlm-sandbox
resources:
  - ../../../base/externalsecrets   # the 6 testbed-* ExternalSecrets (shared)
  - clustersecretstore.yaml         # dev Vault store + root token Secret
  - seed-job.yaml
