apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: testbed-scripts
    files:
      - init-testbed.sh=init-testbed.sh
      - generate-certs.sh=generate-certs.sh
      - docker-entrypoint.sh=xrootd/docker-entrypoint.sh
      - bootstrap-db.py=rucio/bootstrap-db.py
generatorOptions:
  disableNameSuffixHash: true
