image:
  repository: mgajekcern/rucio-client-docker-kubectl
  tag: "3867d9453cff79ce4d3b9354065e1c57402dafc7"
  digest: ""
  pullPolicy: IfNotPresent

fullnameOverride: rucio-client

env: []

volumes: []
volumeMounts: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
