image:
  repository: mgajekcern/rucio-client-docker-kubectl
  tag: "latest"
  digest: ""
  pullPolicy: IfNotPresent

fullnameOverride: rucio-client

env:
  - name: REQUESTS_CA_BUNDLE
    value: /etc/grid-security/certificates/rucio_ca.pem
  - name: AWS_CA_BUNDLE
    value: /etc/pki/tls/cert.pem

volumes: []
volumeMounts: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
