image:
  repository: mgajekcern/rucio-client-docker-kubectl
  tag: "latest"
  digest: ""
  pullPolicy: IfNotPresent

fullnameOverride: rucio-client

env:
  - name: REQUESTS_CA_BUNDLE
    value: /etc/pki/tls/certs/ca-bundle.crt

volumes: []
volumeMounts: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
