apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# DB stage for sandbox — postgresql only, namespace pinned.
resources:
  - ../../flux-system/gitrepository.yaml
  - ../../sources/helmrepositories.yaml
  - ../../components/postgresql.yaml
patches:
  - target: { kind: HelmRelease }
    patch: |
      - op: replace
        path: /spec/targetNamespace
        value: dep-dlm-sandbox
