apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dep-dlm-production
resources:
  - gateway.yaml
  - httproute-rucio-server.yaml
  - httproute-fts.yaml
  - healthcheckpolicy-rucio-server.yaml
  - healthcheckpolicy-fts.yaml
