idp:
  internal: false                                       # external SSO/IdP
  issuerUrl: "https://idp.example.org/realms/dep-dlm"   # TODO
storage:
  xrootd: { internal: false }
  webdav: { internal: false }
tokenFlow: managed

postgresql:
  primary:
    persistence: { enabled: true, size: 10Gi }     # not ephemeral
