apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rucio-server-cfg
spec:
  refreshInterval: 1h
  secretStoreRef: { name: dep-dlm-vault, kind: ClusterSecretStore }
  target: { name: rucio-server-cfg, creationPolicy: Owner }
  dataFrom:
    - extract: { key: dep-dlm/rucio }
