apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: testbed-configs
spec:
  refreshInterval: 1h
  secretStoreRef: { name: dep-dlm-vault, kind: ClusterSecretStore }
  target: { name: testbed-configs, creationPolicy: Owner }
  dataFrom:
    - extract: { key: dep-dlm/configs }
