variable "project_id" {
  description = "GCP project ID for the production environment (from deploy/terraform/bootstrap output project_ids.production) — must be a DIFFERENT project than staging, not a var flip on the same one"
  type        = string
}

variable "region" {
  description = "GCP region — must match deploy/terraform/bootstrap output regions.production exactly. No default, deliberately — see environments/staging/variables.tf's identical note."
  type        = string
}

variable "network_id" {
  description = "VPC network ID from deploy/terraform/bootstrap output network_ids.production"
  type        = string
}

variable "subnet_id" {
  description = "GKE subnet ID from deploy/terraform/bootstrap output subnet_ids.production"
  type        = string
}

variable "pods_range_name" {
  description = "Secondary IP range name for GKE pods, from deploy/terraform/bootstrap output pods_range_names.production"
  type        = string
}

variable "services_range_name" {
  description = "Secondary IP range name for GKE services, from deploy/terraform/bootstrap output services_range_names.production"
  type        = string
}

variable "environment" {
  description = "Environment name, used to derive resource name prefixes"
  type        = string
  default     = "production"
}

variable "deletion_protection" {
  description = "Should default true for production once this environment is actually used — left false here only because this whole environment is an unvalidated placeholder"
  type        = bool
  default     = false
}

# Needed by module "secrets"

variable "bootstrap_userpass_pwd" {
  description = "Bootstrap ddmlab userpass password baked into rucio.cfg's [client]/[bootstrap] sections — human-provided, not generated by Terraform"
  type        = string
  sensitive   = true
}

variable "oidc_issuer" {
  description = "OIDC issuer URL (e.g. the EGI Check-in Dev or LS AAI realm) shared by rucio.cfg, fts3config and idpsecrets.json"
  type        = string
}

variable "oidc_client_id" {
  description = "OIDC client ID for this environment's rucio/fts client registration"
  type        = string
}

variable "oidc_client_secret" {
  description = "OIDC client secret for this environment's rucio/fts client registration — human-provided, not generated by Terraform"
  type        = string
  sensitive   = true
}

variable "token_mode" {
  description = "managed (exchange, FTS manages token lifecycle) | unmanaged (client_credentials, AllowNonManagedTokens=True) — mirrors the sandbox's TOKEN_MODE"
  type        = string
  default     = "managed"
  validation {
    condition     = contains(["managed", "unmanaged"], var.token_mode)
    error_message = "token_mode must be 'managed' or 'unmanaged'."
  }
}
