apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fts.fullname" . }}
  labels:
    app: {{ include "fts.name" . }}
    instance: {{ include "fts.fullname" . }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "fts.name" . }}
      instance: {{ include "fts.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "fts.name" . }}
        instance: {{ include "fts.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      hostname: {{ include "fts.fullname" . }}
      containers:
        - name: fts
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
            - |
              # CA trust injection
              if ! grep -q "5fca1cb1" /etc/pki/tls/certs/ca-bundle.crt; then
                cat /etc/grid-security/certificates/5fca1cb1.0 >> /etc/pki/tls/certs/ca-bundle.crt
              fi

              /docker-entrypoint.sh
          env:
            {{- toYaml .Values.env | nindent 12 }}
            - name: FTS_DB_HOST
              value: {{ .Values.ftsdbHost | quote }}
          ports:
            - name: rest
              containerPort: 8446
              protocol: TCP
            - name: monitoring
              containerPort: 8449
              protocol: TCP
          volumeMounts:
            {{- range $mount := .Values.volumeMounts }}
            - name: {{ $mount.name }}
              mountPath: {{ $mount.mountPath }}
              {{- if hasKey $mount "subPath" }}
              subPath: {{ tpl $mount.subPath $ }}
              {{- end }}
              {{- if hasKey $mount "readOnly" }}
              readOnly: {{ $mount.readOnly }}
              {{- end }}
            {{- end }}
          {{- if .Values.healthcheck.enabled }}
          readinessProbe:
            exec:
              command: ["curl", "-sk", "https://localhost:8446/whoami"]
            initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.periodSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
