name=data
rootPath=/data
accessPoints=/data
orgs=https://aai-dev.egi.eu/auth/realms/egi
fineGrainedAuthzEnabled=true
wlcgScopeAuthzEnabled=true
anonymousReadEnabled=true
authenticatedReadEnabled=true
