apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  labels: { dep-dlm.component: keycloak }
  annotations: { argocd.argoproj.io/sync-wave: "5" }
spec:
  project: default
  sources:
    - repoURL: https://github.com/ri-scale/dep-dlm-testbed.git
      targetRevision: feat/gitops-deployment-blueprint
      path: deploy/helm-charts/keycloak
      helm: { valueFiles: [ $values/deploy/gitops/base/values/keycloak.yaml ] }
    - repoURL: https://github.com/ri-scale/dep-dlm-testbed.git
      targetRevision: feat/gitops-deployment-blueprint
      ref: values
  destination: { server: https://kubernetes.default.svc, namespace: dep-dlm-PLACEHOLDER }
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true, ServerSideApply=true ]
