[Global]
onmissing = passthrough
audience = xrd3, xrd4, fts, rucio

[Issuer LSAAI]
issuer = https://login.aai.lifescience-ri.eu/oidc/
base_path = /data
map_subject = True
# default_user is a fallback, but 'u *' in authdb is more robust
default_user = xrootd
