apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rucio-charts-fork
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/mgajek-cern/helm-charts.git
  ref:
    branch: master
