apiVersion: v2
name: xrootd
description: >
  XRootD server for the DEP DLM testbed.
  Supports SciTokens/OIDC auth mode.
type: application
version: 0.1.0
appVersion: "5"
keywords:
  - rucio
  - xrootd
  - storage
  - scitokens
