name: Terraform destroy (production)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "production" to confirm you want to destroy the production environment'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    uses: ./.github/workflows/_terraform-destroy.yml
    with:
      tf_env: production
      environment_name: production
      confirm: ${{ inputs.confirm }}
