apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: testbed-patches
    files:
      - fts--JobBuilder.py=fts/JobBuilder.py
      - fts--cloud.py=fts/cloud.py
      - fts--cloudStorage.py=fts/cloudStorage.py
      - fts--middleware.py=fts/middleware.py
      - fts--openidconnect.py=fts/openidconnect.py
      - fts--tokenproviders.py=fts/tokenproviders.py
      - rucio--constants.py=rucio/constants.py
      - rucio--fts3.py=rucio/fts3.py
      - rucio--oidc.py=rucio/oidc.py
      - rucio--rse.py=rucio/rse.py
generatorOptions:
  disableNameSuffixHash: true
