name=data
rootPath=/data
accessPoints=/data
orgs=https://login.aai.lifescience-ri.eu/oidc/
fineGrainedAuthzEnabled=true
wlcgScopeAuthzEnabled=true
anonymousReadEnabled=true
authenticatedReadEnabled=true
